services:
  # 2番目の階層、作りたいコンテナを定義する。任意の名前をつけられる。
  php-app:
    # コンテナ名
    container_name: run-php-app
    # ビルドするDockerfileの場所
    build: ./app
    # ポート
    ports:
      - "18080:80"
    # ローカルPCとコンテナ間でディレクトリをバインド
    volumes:
      - ./app/src:/var/www/html/
    # 利用するネットワーク
    networks:
      - php-mysql-networks
    # 指定したサービスの後にコンテナを起動
    depends_on:
      - php-db
  php-db:
    image: mysql:8.0
    container_name: run-php-db
    ports:
      - "3307:3306"
    # コンテナの環境変数を指定
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test_db
    # DBの永続化のボリュームを指定
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    networks:
      - php-mysql-networks
  # DBをUIで確認できるツール
  php-adminer:
    container_name: adminer
    image: adminer:4.8.1
    ports:
      - 8081:8080
    networks:
      - php-mysql-networks
    depends_on:
      - php-db
# 任意のボリュームを作る(DBの永続化用)
volumes:
  mysql-data:
# 任意のネットワークを作る(わかりやすくするため)
networks:
  php-mysql-networks:
